name: Script workflow
on:
  workflow_dispatch:
jobs:
  script-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Script workflow
        run: echo "Running Script Workflow!"

      - name: Run python Script workflow
        run: python script.py
