name: Dependent Multi jobs workflow

on:
  workflow_dispatch:

jobs:
  first-workflow-job:
    runs-on: ubuntu-latest
    steps:
      - name: First jobs workflow
        run: echo "Hello, Multijobs First workflow!"

  second-workflow-job:
    runs-on: ubuntu-latest
    needs: [first-workflow-job]
    steps:
      - name: Second jobs workflow
        run: echo "Hello, Multijobs! second workflow!"
  third-workflow-job:
    runs-on: ubuntu-latest
    needs: [first-workflow-job, second-workflow-job]
    needs: third-workflow-job
    steps:
      - name: Third jobs workflow
        run: echo "Hello, Multijobs! third workflow!"
