name: Conditional workflow

on:
  push:
    paths:
      - "backend/**"

jobs:
  conditional-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Build backend image
        uses: parvezmiazy/gh-tutorial/.github/workflows/11-reusable-workflow.yml@main
